// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain01 "github.com/justiandre/poc-go-validate-arch/pkg/domain/domain01"
	mock "github.com/stretchr/testify/mock"
)

// ServiceSave is an autogenerated mock type for the serviceSave type
type ServiceSave struct {
	mock.Mock
}

// Save provides a mock function with given fields: entity
func (_m *ServiceSave) Save(entity domain01.Domain01) string {
	ret := _m.Called(entity)

	var r0 string
	if rf, ok := ret.Get(0).(func(domain01.Domain01) string); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewServiceSave interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceSave creates a new instance of ServiceSave. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceSave(t mockConstructorTestingTNewServiceSave) *ServiceSave {
	mock := &ServiceSave{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
