// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServiceDelete is an autogenerated mock type for the serviceDelete type
type ServiceDelete struct {
	mock.Mock
}

// DeleteByID provides a mock function with given fields: id
func (_m *ServiceDelete) DeleteByID(id string) {
	_m.Called(id)
}

type mockConstructorTestingTNewServiceDelete interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceDelete creates a new instance of ServiceDelete. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceDelete(t mockConstructorTestingTNewServiceDelete) *ServiceDelete {
	mock := &ServiceDelete{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
