// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain01 "github.com/justiandre/poc-go-validate-arch/pkg/domain/domain01"
	mock "github.com/stretchr/testify/mock"
)

// ServiceFind is an autogenerated mock type for the serviceFind type
type ServiceFind struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *ServiceFind) FindByID(id string) domain01.Domain01 {
	ret := _m.Called(id)

	var r0 domain01.Domain01
	if rf, ok := ret.Get(0).(func(string) domain01.Domain01); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain01.Domain01)
	}

	return r0
}

type mockConstructorTestingTNewServiceFind interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceFind creates a new instance of ServiceFind. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceFind(t mockConstructorTestingTNewServiceFind) *ServiceFind {
	mock := &ServiceFind{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
