// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain02 "github.com/justiandre/poc-go-validate-arch/pkg/domain/domain02"
	mock "github.com/stretchr/testify/mock"
)

// ServiceDomain02Save is an autogenerated mock type for the serviceDomain02Save type
type ServiceDomain02Save struct {
	mock.Mock
}

// Save provides a mock function with given fields: entity
func (_m *ServiceDomain02Save) Save(entity domain02.Domain02) string {
	ret := _m.Called(entity)

	var r0 string
	if rf, ok := ret.Get(0).(func(domain02.Domain02) string); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewServiceDomain02Save interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceDomain02Save creates a new instance of ServiceDomain02Save. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceDomain02Save(t mockConstructorTestingTNewServiceDomain02Save) *ServiceDomain02Save {
	mock := &ServiceDomain02Save{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
